import pymysql
db=pymysql.connect("localhost","root","***********","acad_assign")
cursor=db.cursor()
cursor.execute(  "insert into book(userid int,titleid int,location char(25),genre int) values(101,01,'argentina','adventure')"  )
cursor.execute(  "insert into title(titleid int,title int,publisherid char(20),publisher_year int) values(102,02,'mohit',2002)" )
cursor.execute("select * from book")
result=cursor.fetchall()
print(result)
db.commit()
db.close()
#
# db=py.connect("localhost","root","**************","library")
# cursor=db.cursor()
#
# cursor.execute("insert into book values(001,'looking for alaska','india','fiction')")
# cursor.execute("insert into titles values(001,'looking for alaska','1001',101,2005)")
# cursor.execute("insert into publishers values(001,'abc','london',10002,11001)")
# cursor.execute("insert into zip_code values(001,'ambala','haryana',133203)")
# cursor.execute("insert into auther_titles values(001,10010,1012012)")
# cursor.execute("insert into authors values(001,'john','null','green')")
# cursor.execute("select * from book")
# result=cursor.fetchall()
# print(result)
# db.commit()
# db.close()